pipeline {
	agent any

    environment {
		MY_ENV_VAR = 'ci for my rocket app'
    }

    stages {
		stage('Checkout') {
			steps {
				script {
					def gitRepoUrl = 'https://github.com/your-username/rocket-app.git'

                    checkout([$class: 'GitSCM',
                        branches: [[name: '*/master']],
                        userRemoteConfigs: [[url: gitRepoUrl]],
                        extensions: [[$class: 'CleanBeforeCheckout'], [$class: 'CloneOption', noTags: false, shallow: true, depth: 1]]
                    ])
                }
            }
        }

        stage('Build') {
			steps {
				sh './mvnw clean package'
            }
        }

        stage('Test') {
			steps {
				sh './mvnw test'
            }
        }

        stage('Deploy') {
			steps {
				sh 'echo "Value of ENV Variable is $MY_ENV_VAR"'
            }
        }
    }

    post {
		success {
			echo 'Pipeline succeeded!'
        }
        failure {
			echo 'Pipeline failed!'
        }
    }
}
